-- Clear existing categories and seed with real forum categories
DELETE FROM categories;

INSERT INTO categories (name, slug, icon, description) VALUES
  ('Amiga', 'amiga', '🖥️', 'Amiga-tietokoneet ja pelit'),
  ('Arcade', 'arcade', '🕹️', 'Kolikkopeliautomaatit ja arcade-pelit'),
  ('SNES', 'snes', '🎮', 'Super Nintendo Entertainment System'),
  ('Playstation 1', 'playstation-1', '💿', 'Sony Playstation'),
  ('Playstation 2', 'playstation-2', '📀', 'Sony Playstation 2'),
  ('Playstation 3', 'playstation-3', '🎮', 'Sony Playstation 3'),
  ('Playstation 4', 'playstation-4', '🎮', 'Sony Playstation 4'),
  ('Playstation 5', 'playstation-5', '🎮', 'Sony Playstation 5'),
  ('Nintendo DS', 'nintendo-ds', '📱', 'Nintendo DS ja 3DS'),
  ('Gamecube', 'gamecube', '🟪', 'Nintendo Gamecube'),
  ('Revolution', 'revolution', '🎯', 'Nintendo Revolution'),
  ('Nintendo 64', 'nintendo-64', '🕹️', 'Nintendo 64'),
  ('Nintendo Switch', 'nintendo-switch', '🔴', 'Nintendo Switch'),
  ('Nintendo Wii', 'nintendo-wii', '🏠', 'Nintendo Wii'),
  ('NES', 'nes', '🕹️', 'Nintendo Entertainment System'),
  ('Gameboy', 'gameboy', '🟩', 'Nintendo Gameboy'),
  ('Xbox', 'xbox', '💚', 'Microsoft Xbox'),
  ('Xbox 360', 'xbox-360', '💚', 'Microsoft Xbox 360'),
  ('Xbox One', 'xbox-one', '💚', 'Microsoft Xbox One'),
  ('Xbox Series', 'xbox-series', '💚', 'Microsoft Xbox Series X/S'),
  ('Dreamcast', 'dreamcast', '🌀', 'Sega Dreamcast'),
  ('PC-pelit', 'pc-pelit', '💻', 'PC-pelaaminen'),
  ('Selainpelit', 'selainpelit', '🌐', 'Selainpohjaiset pelit'),
  ('Mobiilipelit', 'mobiilipelit', '📱', 'Mobiilipelit'),
  ('Steamdeck', 'steamdeck', '🎮', 'Valve Steam Deck'),
  ('Gamepark', 'gamepark', '🎮', 'Gamepark-käsikonsolit'),
  ('N.Gage', 'n-gage', '📞', 'Nokia N-Gage'),
  ('8-bit Commodore', '8-bit-commodore', '💾', 'Commodore 64 ja muut 8-bittiset'),
  ('Leffat', 'leffat', '🎬', 'Elokuvat ja TV-sarjat'),
  ('Sarjakuvat', 'sarjakuvat', '📖', 'Sarjakuvat ja manga'),
  ('Musiikki', 'musiikki', '🎵', 'Musiikki ja bändit'),
  ('Internet', 'internet', '🌍', 'Internet ja nettikulttuuri'),
  ('Figut', 'figut', '🧸', 'Figuurit ja keräily'),
  ('Korttipelit', 'korttipelit', '🃏', 'Keräily- ja korttipelit'),
  ('Lautapelit', 'lautapelit', '🎲', 'Lautapelit'),
  ('Roolipelit', 'roolipelit', '🐉', 'Pöytäroolipelit'),
  ('Kirjat ja lehdet', 'kirjat-ja-lehdet', '📚', 'Kirjat, lehdet ja lukeminen'),
  ('Pokemonit', 'pokemonit', '⚡', 'Pokémon-pelit ja keräily'),
  ('Urheilu', 'urheilu', '⚽', 'Urheilu ja liikunta'),
  ('Vimpaimet', 'vimpaimet', '🔧', 'Laitteet ja vimpaimet'),
  ('Off-topic', 'off-topic', '💬', 'Vapaa keskustelu');
