-- Baseline trophies imported from legacy board HTML
-- Source file used during migration authoring: /Users/eero/Desktop/trophies.html

CREATE TABLE IF NOT EXISTS trophies (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  points integer NOT NULL DEFAULT 0,
  icon_path text,
  source text NOT NULL DEFAULT 'legacy',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS profile_trophies (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  trophy_id bigint NOT NULL REFERENCES trophies(id) ON DELETE CASCADE,
  awarded_at timestamptz NOT NULL DEFAULT now(),
  awarded_source text NOT NULL DEFAULT 'import',
  UNIQUE(profile_id, trophy_id)
);

CREATE INDEX IF NOT EXISTS idx_profile_trophies_profile_id ON profile_trophies(profile_id);
CREATE INDEX IF NOT EXISTS idx_profile_trophies_trophy_id ON profile_trophies(trophy_id);

GRANT SELECT ON trophies TO authenticated;
GRANT SELECT ON profile_trophies TO authenticated;

ALTER TABLE trophies ENABLE ROW LEVEL SECURITY;
ALTER TABLE profile_trophies ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated can read trophies" ON trophies;
CREATE POLICY "Authenticated can read trophies" ON trophies
  FOR SELECT USING (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Authenticated can read profile_trophies" ON profile_trophies;
CREATE POLICY "Authenticated can read profile_trophies" ON profile_trophies
  FOR SELECT USING (auth.uid() IS NOT NULL);

INSERT INTO trophies (code, name, points, icon_path, source) VALUES
  ('elgrandehefedel8-bitcommodore', 'El Grande Hefe Del 8-bit commodore', 20, 'templates/cute/images/honours/elgrandehefedel8-bitcommodore.gif', 'legacy_html'),
  ('elgrandehefedelamiga', 'El Grande Hefe Del Amiga', 20, 'templates/cute/images/honours/elgrandehefedelamiga.gif', 'legacy_html'),
  ('elgrandehefedelarcade', 'El Grande Hefe Del Arcade', 20, 'templates/cute/images/honours/elgrandehefedelarcade.gif', 'legacy_html'),
  ('elgrandehefedeldreamcast', 'El Grande Hefe Del Dreamcast', 20, 'templates/cute/images/honours/elgrandehefedeldreamcast.gif', 'legacy_html'),
  ('elgrandehefedelfigut', 'El Grande Hefe Del Figut', 20, 'templates/cute/images/honours/elgrandehefedelfigut.gif', 'legacy_html'),
  ('elgrandehefedelgameboy', 'El Grande Hefe Del Gameboy', 20, 'templates/cute/images/honours/elgrandehefedelgameboy.gif', 'legacy_html'),
  ('elgrandehefedelgamecube', 'El Grande Hefe Del Gamecube', 20, 'templates/cute/images/honours/elgrandehefedelgamecube.gif', 'legacy_html'),
  ('elgrandehefedelinternet', 'El Grande Hefe Del Internet', 20, 'templates/cute/images/honours/elgrandehefedelinternet.gif', 'legacy_html'),
  ('elgrandehefedelkirjatjalehdet', 'El Grande Hefe Del Kirjat ja lehdet', 20, 'templates/cute/images/honours/elgrandehefedelkirjatjalehdet.gif', 'legacy_html'),
  ('elgrandehefedelkorttipelit', 'El Grande Hefe Del Korttipelit', 20, 'templates/cute/images/honours/elgrandehefedelkorttipelit.gif', 'legacy_html'),
  ('elgrandehefedellautapelit', 'El Grande Hefe Del Lautapelit', 20, 'templates/cute/images/honours/elgrandehefedellautapelit.gif', 'legacy_html'),
  ('elgrandehefedelleffat', 'El Grande Hefe Del Leffat', 20, 'templates/cute/images/honours/elgrandehefedelleffat.gif', 'legacy_html'),
  ('elgrandehefedelmobiilipelit', 'El Grande Hefe Del Mobiilipelit', 20, 'templates/cute/images/honours/elgrandehefedelmobiilipelit.gif', 'legacy_html'),
  ('elgrandehefedelmusiikki', 'El Grande Hefe Del Musiikki', 20, 'templates/cute/images/honours/elgrandehefedelmusiikki.gif', 'legacy_html'),
  ('elgrandehefedelnes', 'El Grande Hefe Del Nes', 20, 'templates/cute/images/honours/elgrandehefedelnes.gif', 'legacy_html'),
  ('elgrandehefedelnintendo64', 'El Grande Hefe Del Nintendo 64', 20, 'templates/cute/images/honours/elgrandehefedelnintendo64.gif', 'legacy_html'),
  ('elgrandehefedelnintendods', 'El Grande Hefe Del Nintendo ds', 20, 'templates/cute/images/honours/elgrandehefedelnintendods.gif', 'legacy_html'),
  ('elgrandehefedeloff-topic', 'El Grande Hefe Del Off-topic', 20, 'templates/cute/images/honours/elgrandehefedeloff-topic.gif', 'legacy_html'),
  ('elgrandehefedelpc-pelit', 'El Grande Hefe Del Pc-pelit', 20, 'templates/cute/images/honours/elgrandehefedelpc-pelit.gif', 'legacy_html'),
  ('elgrandehefedelplaystation1', 'El Grande Hefe Del Playstation 1', 20, 'templates/cute/images/honours/elgrandehefedelplaystation1.gif', 'legacy_html'),
  ('elgrandehefedelplaystation2', 'El Grande Hefe Del Playstation 2', 20, 'templates/cute/images/honours/elgrandehefedelplaystation2.gif', 'legacy_html'),
  ('elgrandehefedelpokemonit', 'El Grande Hefe Del Pokemonit', 20, 'templates/cute/images/honours/elgrandehefedelpokemonit.gif', 'legacy_html'),
  ('elgrandehefedelpsp', 'El Grande Hefe Del Psp', 20, 'templates/cute/images/honours/elgrandehefedelpsp.gif', 'legacy_html'),
  ('elgrandehefedelroolipelit', 'El Grande Hefe Del Roolipelit', 20, 'templates/cute/images/honours/elgrandehefedelroolipelit.gif', 'legacy_html'),
  ('elgrandehefedelsarjakuvat', 'El Grande Hefe Del Sarjakuvat', 20, 'templates/cute/images/honours/elgrandehefedelsarjakuvat.gif', 'legacy_html'),
  ('elgrandehefedelselainpelit', 'El Grande Hefe Del Selainpelit', 20, 'templates/cute/images/honours/elgrandehefedelselainpelit.gif', 'legacy_html'),
  ('elgrandehefedelsnes', 'El Grande Hefe Del Snes', 20, 'templates/cute/images/honours/elgrandehefedelsnes.gif', 'legacy_html'),
  ('elgrandehefedelurheilu', 'El Grande Hefe Del Urheilu', 20, 'templates/cute/images/honours/elgrandehefedelurheilu.gif', 'legacy_html'),
  ('elgrandehefedelxbox', 'El Grande Hefe Del Xbox', 20, 'templates/cute/images/honours/elgrandehefedelxbox.gif', 'legacy_html'),
  ('elhefedel8-bitcommodore', 'El Hefe Del 8-bit commodore', 10, 'templates/cute/images/honours/elhefedel8-bitcommodore.gif', 'legacy_html'),
  ('elhefedelamiga', 'El Hefe Del Amiga', 10, 'templates/cute/images/honours/elhefedelamiga.gif', 'legacy_html'),
  ('elhefedelarcade', 'El Hefe Del Arcade', 10, 'templates/cute/images/honours/elhefedelarcade.gif', 'legacy_html'),
  ('elhefedeldreamcast', 'El Hefe Del Dreamcast', 10, 'templates/cute/images/honours/elhefedeldreamcast.gif', 'legacy_html'),
  ('elhefedelfigut', 'El Hefe Del Figut', 10, 'templates/cute/images/honours/elhefedelfigut.gif', 'legacy_html'),
  ('elhefedelgameboy', 'El Hefe Del Gameboy', 10, 'templates/cute/images/honours/elhefedelgameboy.gif', 'legacy_html'),
  ('elhefedelgamecube', 'El Hefe Del Gamecube', 10, 'templates/cute/images/honours/elhefedelgamecube.gif', 'legacy_html'),
  ('elhefedelinternet', 'El Hefe Del Internet', 10, 'templates/cute/images/honours/elhefedelinternet.gif', 'legacy_html'),
  ('elhefedelkirjatjalehdet', 'El Hefe Del Kirjat ja lehdet', 10, 'templates/cute/images/honours/elhefedelkirjatjalehdet.gif', 'legacy_html'),
  ('elhefedelkorttipelit', 'El Hefe Del Korttipelit', 10, 'templates/cute/images/honours/elhefedelkorttipelit.gif', 'legacy_html'),
  ('elhefedellautapelit', 'El Hefe Del Lautapelit', 10, 'templates/cute/images/honours/elhefedellautapelit.gif', 'legacy_html'),
  ('elhefedelleffat', 'El Hefe Del Leffat', 10, 'templates/cute/images/honours/elhefedelleffat.gif', 'legacy_html'),
  ('elhefedelmobiilipelit', 'El Hefe Del Mobiilipelit', 10, 'templates/cute/images/honours/elhefedelmobiilipelit.gif', 'legacy_html'),
  ('elhefedelmusiikki', 'El Hefe Del Musiikki', 10, 'templates/cute/images/honours/elhefedelmusiikki.gif', 'legacy_html'),
  ('elhefedelnes', 'El Hefe Del Nes', 10, 'templates/cute/images/honours/elhefedelnes.gif', 'legacy_html'),
  ('elhefedelnintendo64', 'El Hefe Del Nintendo 64', 10, 'templates/cute/images/honours/elhefedelnintendo64.gif', 'legacy_html'),
  ('elhefedelnintendods', 'El Hefe Del Nintendo ds', 10, 'templates/cute/images/honours/elhefedelnintendods.gif', 'legacy_html'),
  ('elhefedeloff-topic', 'El Hefe Del Off-topic', 10, 'templates/cute/images/honours/elhefedeloff-topic.gif', 'legacy_html'),
  ('elhefedelpc-pelit', 'El Hefe Del Pc-pelit', 10, 'templates/cute/images/honours/elhefedelpc-pelit.gif', 'legacy_html'),
  ('elhefedelplaystation1', 'El Hefe Del Playstation 1', 10, 'templates/cute/images/honours/elhefedelplaystation1.gif', 'legacy_html'),
  ('elhefedelplaystation2', 'El Hefe Del Playstation 2', 10, 'templates/cute/images/honours/elhefedelplaystation2.gif', 'legacy_html'),
  ('elhefedelpokemonit', 'El Hefe Del Pokemonit', 10, 'templates/cute/images/honours/elhefedelpokemonit.gif', 'legacy_html'),
  ('elhefedelpsp', 'El Hefe Del Psp', 10, 'templates/cute/images/honours/elhefedelpsp.gif', 'legacy_html'),
  ('elhefedelroolipelit', 'El Hefe Del Roolipelit', 10, 'templates/cute/images/honours/elhefedelroolipelit.gif', 'legacy_html'),
  ('elhefedelsarjakuvat', 'El Hefe Del Sarjakuvat', 10, 'templates/cute/images/honours/elhefedelsarjakuvat.gif', 'legacy_html'),
  ('elhefedelselainpelit', 'El Hefe Del Selainpelit', 10, 'templates/cute/images/honours/elhefedelselainpelit.gif', 'legacy_html'),
  ('elhefedelsnes', 'El Hefe Del Snes', 10, 'templates/cute/images/honours/elhefedelsnes.gif', 'legacy_html'),
  ('elhefedelurheilu', 'El Hefe Del Urheilu', 10, 'templates/cute/images/honours/elhefedelurheilu.gif', 'legacy_html'),
  ('elhefedelxbox', 'El Hefe Del Xbox', 10, 'templates/cute/images/honours/elhefedelxbox.gif', 'legacy_html'),
  ('flooder', 'Flooder', 20, 'templates/cute/images/honours/flooder.gif', 'legacy_html'),
  ('freakon1vjuhlija', 'Freak On! 1V juhlija', 20, 'templates/cute/images/honours/freakon1vjuhlija.gif', 'legacy_html'),
  ('freakon2vjuhlija', 'Freak On! 2V juhlija', 20, 'templates/cute/images/honours/freakon2vjuhlija.gif', 'legacy_html'),
  ('freakon3vjuhlija', 'Freak On! 3V juhlija', 20, 'templates/cute/images/honours/freakon3vjuhlija.gif', 'legacy_html'),
  ('furyoftheninjacatpiratesosallistuja', 'Fury of the Ninja Cat Pirates osallistuja', 20, 'templates/cute/images/honours/furyoftheninjacatpiratesosallistuja.gif', 'legacy_html'),
  ('h4rdc0r3iiosallistuja', 'H4RDC0R3 II osallistuja', 20, 'templates/cute/images/honours/h4rdc0r3iiosallistuja.gif', 'legacy_html'),
  ('h4rdc0r3osallistuja', 'H4RDC0R3 osallistuja', 20, 'templates/cute/images/honours/h4rdc0r3osallistuja.gif', 'legacy_html'),
  ('hypersharpshooter', 'Hyper Sharp Shooter', 35, 'templates/cute/images/honours/hypersharpshooter.gif', 'legacy_html'),
  ('lahtiexperienceosallistuja', 'Lahti Experience osallistuja', 20, 'templates/cute/images/honours/lahtiexperienceosallistuja.gif', 'legacy_html'),
  ('luckyluckyluke', 'Lucky Lucky Luke', 30, 'templates/cute/images/honours/luckyluckyluke.gif', 'legacy_html'),
  ('luckyluke', 'Lucky Luke', 20, 'templates/cute/images/honours/luckyluke.gif', 'legacy_html'),
  ('nomadicwanderingroamer', 'Nomadic Wandering Roamer', 30, 'templates/cute/images/honours/nomadicwanderingroamer.gif', 'legacy_html'),
  ('roamer', 'Roamer', 10, 'templates/cute/images/honours/roamer.gif', 'legacy_html'),
  ('supersharpshooter', 'Super Sharp Shooter', 25, 'templates/cute/images/honours/supersharpshooter.gif', 'legacy_html'),
  ('suunnistusihopea', 'Suunnistus I Hopea', 40, 'templates/cute/images/honours/suunnistusihopea.gif', 'legacy_html'),
  ('suunnistusikulta', 'Suunnistus I Kulta', 50, 'templates/cute/images/honours/suunnistusikulta.gif', 'legacy_html'),
  ('suunnistusipronssi', 'Suunnistus I Pronssi', 30, 'templates/cute/images/honours/suunnistusipronssi.gif', 'legacy_html'),
  ('suunnistusisuunnistaja', 'Suunnistus I Suunnistaja', 20, 'templates/cute/images/honours/suunnistusisuunnistaja.gif', 'legacy_html'),
  ('suunnistusiihopea', 'Suunnistus II Hopea', 40, 'templates/cute/images/honours/suunnistusiihopea.gif', 'legacy_html'),
  ('suunnistusiikulta', 'Suunnistus II Kulta', 50, 'templates/cute/images/honours/suunnistusiikulta.gif', 'legacy_html'),
  ('suunnistusiipronssi', 'Suunnistus II Pronssi', 30, 'templates/cute/images/honours/suunnistusiipronssi.gif', 'legacy_html'),
  ('suunnistusiisuunnistaja', 'Suunnistus II Suunnistaja', 20, 'templates/cute/images/honours/suunnistusiisuunnistaja.gif', 'legacy_html'),
  ('tsunami', 'Tsunami', 40, 'templates/cute/images/honours/tsunami.gif', 'legacy_html'),
  ('wanderingroamer', 'Wandering Roamer', 20, 'templates/cute/images/honours/wanderingroamer.gif', 'legacy_html'),
  ('xboxlan1.5osallistuja', 'XBOXLAN 1.5 osallistuja', 20, 'templates/cute/images/honours/xboxlan1.5osallistuja.gif', 'legacy_html'),
  ('xboxlan2osallistuja', 'XBOXLAN 2 osallistuja', 20, 'templates/cute/images/honours/xboxlan2osallistuja.gif', 'legacy_html'),
  ('xboxlanosallistuja', 'XBOXLAN osallistuja', 20, 'templates/cute/images/honours/xboxlanosallistuja.gif', 'legacy_html')
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  icon_path = EXCLUDED.icon_path,
  source = EXCLUDED.source;

WITH target_assignments AS (
  SELECT * FROM (VALUES
    ('e-z', 'tsunami'),
    ('e-z', 'freakon1vjuhlija'),
    ('e-z', 'freakon2vjuhlija'),
    ('e-z', 'freakon3vjuhlija'),
    ('e-z', 'h4rdc0r3iiosallistuja'),
    ('e-z', 'h4rdc0r3osallistuja'),
    ('e-z', 'lahtiexperienceosallistuja'),
    ('e-z', 'suunnistusisuunnistaja'),
    ('e-z', 'suunnistusiisuunnistaja'),
    ('e-z', 'wanderingroamer'),
    ('e-z', 'xboxlan1.5osallistuja'),
    ('e-z', 'xboxlanosallistuja'),
    ('e-z', 'elhefedelgameboy'),
    ('e-z', 'elhefedelkorttipelit'),
    ('e-z', 'elhefedellautapelit'),
    ('e-z', 'elhefedelmusiikki'),
    ('e-z', 'elhefedelnintendods'),
    ('e-z', 'elhefedeloff-topic'),
    ('e-z', 'elhefedelplaystation2'),
    ('e-z', 'elhefedelpsp'),
    ('e-z', 'elhefedelxbox'),
    ('subjik', 'suunnistusiikulta'),
    ('subjik', 'freakon1vjuhlija'),
    ('subjik', 'freakon2vjuhlija'),
    ('subjik', 'freakon3vjuhlija'),
    ('subjik', 'h4rdc0r3osallistuja'),
    ('subjik', 'lahtiexperienceosallistuja'),
    ('subjik', 'suunnistusisuunnistaja'),
    ('subjik', 'xboxlan1.5osallistuja'),
    ('subjik', 'xboxlan2osallistuja'),
    ('subjik', 'xboxlanosallistuja'),
    ('subjik', 'elhefedel8-bitcommodore'),
    ('subjik', 'elhefedelnes')
  ) AS v(username, trophy_code)
), matched AS (
  SELECT p.id AS profile_id, t.id AS trophy_id
  FROM target_assignments ta
  JOIN profiles p ON lower(p.username) = lower(ta.username)
  JOIN trophies t ON t.code = ta.trophy_code
)
INSERT INTO profile_trophies (profile_id, trophy_id, awarded_source)
SELECT profile_id, trophy_id, 'legacy_import'
FROM matched
ON CONFLICT (profile_id, trophy_id) DO NOTHING;

CREATE OR REPLACE VIEW admin_trophy_overview AS
SELECT
  t.id,
  t.code,
  t.name,
  t.points,
  t.icon_path,
  t.source,
  COUNT(pt.id)::int AS awarded_count
FROM trophies t
LEFT JOIN profile_trophies pt ON pt.trophy_id = t.id
GROUP BY t.id, t.code, t.name, t.points, t.icon_path, t.source
ORDER BY t.points DESC, t.name ASC;

GRANT SELECT ON admin_trophy_overview TO authenticated;
